
dbServers:
    - displayName: "Vertica"
      connectionUrl: "jdbc:vertica://192.168.57.102:5433/VMart;"

      driver: "com.vertica.jdbc.Driver"
      host: "192.168.57.102"
      port: 5433
      database: "VMart"
      user: "dbadmin"
      password: "password"

      #Needs to be used in conjunction with `encryptionKey`. Please read the extension documentation to generate encrypted password
      #encryptedPassword: ""

      queries:
        - displayName: "Active1"
          queryStmt: "Select NODE_NAME, EVENT_CODE, EVENT_ID, EVENT_POSTED_COUNT from Active_events"
          columns:
            - name: "NODE_NAME"
              type: "metricPathName"

            - name: "EVENT_ID"
              type: "metricPathName"

            - name: "EVENT_CODE"
              type: "metricValue"

            - name: "EVENT_POSTED_COUNT"
              type: "metricValue"

        - displayName: "DiskStorage1"
          queryStmt: "Select NODE_NAME, STORAGE_USAGE, RANK, THROUGHPUT, LATENCY, DISK_BLOCK_SIZE_BYTES, DISK_SPACE_USED_BLOCKS, DISK_SPACE_USED_MB, DISK_SPACE_FREE_BLOCKS, DISK_SPACE_FREE_MB, DISK_SPACE_FREE_PERCENT from DISK_STORAGE"
          columns:
            - name: "NODE_NAME"
              type: "metricPathName"

            - name: "STORAGE_USAGE"
              type: "metricPathName"

            - name: "RANK"
              type: "metricValue"

            - name: "THROUGHPUT"
              type: "metricValue"

            - name: "LATENCY"
              type: "metricValue"

            - name: "DISK_BLOCK_SIZE_BYTES"
              type: "metricValue"

            - name: "DISK_SPACE_USED_BLOCKS"
              type: "metricValue"

            - name: "DISK_SPACE_USED_MB"
              type: "metricValue"

            - name: "DISK_SPACE_FREE_BLOCKS"
              type: "metricValue"

            - name: "DISK_SPACE_FREE_MB"
              type: "metricValue"

            - name: "DISK_SPACE_FREE_PERCENT"
              type: "metricValue"

        - displayName: "HostResources1"
          queryStmt: "Select HOST_NAME, OPEN_FILES_LIMIT, THREADS_LIMIT, CORE_FILE_LIMIT_MAX_SIZE_BYTES, PROCESSOR_COUNT, OPENED_FILE_COUNT, OPENED_SOCKET_COUNT, OPENED_NONFILE_NONSOCKET_COUNT, TOTAL_MEMORY_BYTES, TOTAL_MEMORY_FREE_BYTES,  TOTAL_BUFFER_MEMORY_BYTES, TOTAL_MEMORY_CACHE_BYTES, TOTAL_SWAP_MEMORY_BYTES, TOTAL_SWAP_MEMORY_FREE_BYTES, DISK_SPACE_FREE_MB, DISK_SPACE_USED_MB, DISK_SPACE_TOTAL_MB from HOST_RESOURCES"
          columns:
            - name: "HOST_NAME"
              type: "metricPathName"

            - name: "OPEN_FILES_LIMIT"
              type: "metricValue"

            - name: "THREADS_LIMIT"
              type: "metricValue"

            - name: "CORE_FILE_LIMIT_MAX_SIZE_BYTES"
              type: "metricValue"

            - name: "PROCESSOR_COUNT"
              type: "metricValue"

            - name: "OPENED_FILE_COUNT"
              type: "metricValue"

            - name: "OPENED_SOCKET_COUNT"
              type: "metricValue"

            - name: "OPENED_NONFILE_NONSOCKET_COUNT"
              type: "metricValue"

            - name: "TOTAL_MEMORY_BYTES"
              type: "metricValue"

            - name: "TOTAL_MEMORY_FREE_BYTES"
              type: "metricValue"

            - name: "TOTAL_BUFFER_MEMORY_BYTES"
              type: "metricValue"

            - name: "TOTAL_MEMORY_CACHE_BYTES"
              type: "metricValue"

            - name: "TOTAL_SWAP_MEMORY_BYTES"
              type: "metricValue"

            - name: "TOTAL_SWAP_MEMORY_FREE_BYTES"
              type: "metricValue"

            - name: "DISK_SPACE_FREE_MB"
              type: "metricValue"

            - name: "DISK_SPACE_USED_MB"
              type: "metricValue"

            - name: "DISK_SPACE_TOTAL_MB"
              type: "metricValue"

        - displayName: "IO_USAGE"
          queryStmt: "Select NODE_NAME, READ_KBYTES_PER_SEC, WRITTEN_KBYTES_PER_SEC from IO_USAGE"
          columns:
            - name: "NODE_NAME"
              type: "metricPathName"

            - name: "READ_KBYTES_PER_SEC"
              type: "metricValue"

            - name: "WRITTEN_KBYTES_PER_SEC"
              type: "metricValue"

        - displayName: "NODE_STATUS"
          queryStmt: "Select NODE_NAME, NODE_STATE from NODE_STATES"
          columns:
            - name: "NODE_NAME"
              type: "metricPathName"

            - name: "NODE_STATE"
              type: "metricValue"


#  NODE STATUS :
# INITIALIZING : 0
#           UP : 1
#        READY : 2
#       UNSAFE : 3
#     SHUTDOWN : 4
#   RECOVERING : 5
#         NULL : 6

numberOfThreads: 5

#Needs to be used in conjunction with `encryptedPassword`. Please read the extension documentation to generate encrypted password
#encryptionKey: "welcome"


# Make sure the metric prefix ends with a |
#This will create this metric in all the tiers, under this path.
#metricPrefix: "Custom Metrics|SQL|"
#This will create it in specific Tier. Replace <ComponentID> with TierID
#metricPrefix: "Server|Component:<ComponentID>|Custom Metrics|Tibco ASG|"
metricPrefix: "Custom Metrics|Vertica|Test1"